project:
  type: book
  output-dir: docs

book:
  title: "Tidyteam code review principles"
  author: "Davis Vaughan"
  repo-url: https://github.com/DavisVaughan/code-review
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - collaboration/index.qmd
    - part: "How to review a pull request"
      chapters:
      - reviewer/purpose.qmd
      - reviewer/aspects.qmd
      - reviewer/navigate.qmd
      - reviewer/speed.qmd
      - reviewer/comments.qmd
      - reviewer/pushback.qmd
    - part: "How to author a pull request"
      chapters:
      - author/submitting.qmd
      - author/focused.qmd
      - author/handling-comments.qmd
    - issues/index.qmd

format:
  html:
    theme: cosmo

editor: visual

